# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L2y7FH-K9-SEx2u6ydCM4U2ZeQNqnTcA
"""

import pandas as pd
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.datasets import boston_housing
from keras.layers import Dense, Activation
from sklearn.preprocessing import MinMaxScaler

url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
column_names = ['MPG', 'Cyclinders', 'Displacement', 'Horsepower', 'Weight',
                'Acceleration', 'Model Year','Origin']

dataset = pd.read_csv(url, names = column_names, na_values='?',
                      comment= '\t', sep = ' ', skipinitialspace = True)

dataset

mms = MinMaxScaler()
mms.fit(dataset)

dataset = mms.transform(dataset)
df = pd.DataFrame(dataset)
df

X = df.iloc[:, 4:6]
y = df.iloc[:, 0]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

print(X_train.shape)
print(y_train.shape)

model = Sequential()
model.add(Dense(1, input_dim = 2))
model.add(Activation('linear'))

model.compile(loss = 'mse', optimizer = 'sgd')

history = model.fit([X_train], [y_train], epochs = 50, verbose = 1)

predict = model.predict(X_test)
predict

