# -*- coding: utf-8 -*-
"""simple_linear_regression_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oMhxuLthHGsYkMRqPaV0fw16v3V93o30
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('Salary.csv')
df.head()

df.shape

df['YearsExperience'].corr(df['Salary'])

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X, y)

y_pred = regressor.predict(X)

plt.scatter(X, y)
plt.plot(X, y_pred, color = 'red')
plt.title('Salary vs Experience')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.show()

regressor.predict(np.array([[5]]))

from sklearn import metrics  
abs_e = metrics.mean_absolute_error(y, y_pred)
print('Mean Absolute Error: {} '.format(abs_e.astype(int)))

mse = metrics.mean_squared_error(y, y_pred)
print('Mean Squared Error: {} '.format(mse.astype(int)))