# -*- coding: utf-8 -*-
"""simple_linear_regression_keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1loi50305c6JKH_jnD3y2t4_FhJsIRA7k
"""

import pandas as pd
import numpy as ad
import matplotlib.pyplot as plt
import keras as ks

from keras.models import Sequential
from keras.layers import Dense, Activation

z = 100
y = 70 * z
y

X = z+y
X

matrix = ad.full((2,3),5)

matrix

data = {}

type(data)

df = pd.read_csv('Salary.csv')
df.head()

X = df.iloc[:,:-1]
y = df.iloc[:,-1]

model = Sequential()

model.add(Dense(1, input_dim = 1))
model.add(Activation('linear'))

# mse -> min square error, sgd -> Stochastic gradient descent
model.compile(loss='mse', optimizer = 'sgd')

history = model.fit(X,y, epochs = 500, verbose = 1)

pred = model.predict(X)

plt.scatter(X,y)
plt.plot(X, pred, color = 'orange')
plt.show()

y_pred = model.predict([5])
y_pred

model.save('LR_1.h5')